version: '3.3'
services: 
    
  db: 
    image: mariadb 
    volumes:
       - db_data:/var/lib/mysql/
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: StrongPass
      MYSQL_DATABASE: db
      MYSQL_USER: userdb
      MYSQL_PASSWORD: Pass
    container_name: db

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    expose:
      - 80
    volumes:
      - wordpress_files:/var/www/html/
    restart: always
    environment:
      VIRTUAL_HOST: wp.com
      LETSENCRYPT_HOST: wp.com
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: userdb
      WORDPRESS_DB_PASSWORD: Pass
      WORDPRESS_DB_NAME: db
      WORDPRESS_TABLE_PREFIX: prefix_
    container_name: wp

volumes:
  wordpress_files: 
  db_data: 

networks:
  default:
    external:
      name: nginx-proxy
